import os
import sys
import yaml
import yt_dlp
import gc
import torch
from train_vqvae import main as train_vqvae_main
from train_generator import main as train_generator_main

def download_youtube_audio(query, download_dir="DNL", max_results=10):
    """
    Searches YouTube for a given query and downloads the best audio as WAV,
    incorporating a random delay between 1 and 4 seconds between downloads.
    """
    print(f"--- Fetching {max_results} tracks for: '{query}' ---")
    
    if not os.path.exists(download_dir):
        os.makedirs(download_dir)

    # yt-dlp configuration for audio extraction
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': os.path.join(download_dir, '%(title)s.%(ext)s'),
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'wav',
            'preferredquality': '192',
        }],
        'noplaylist': True,
        'default_search': f'ytsearch{max_results}:',
        'quiet': False,
        
        # --- NEW ANTI-RATE-LIMITING SETTINGS ---
        'sleep_interval': 2,        # Minimum sleep time (seconds)
        'max_sleep_interval': 10,   # Maximum sleep time (seconds)
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([query])
        print(f"--- Download Complete. Files saved to {download_dir} ---")
    except Exception as e:
        print(f"Error during YouTube download: {e}")


def update_config_for_new_data(config_path, new_raw_dir):
    """
    Temporarily updates the config.yaml to point to the DNL directory
    so your existing training scripts pick up the downloaded files.
    """
    with open(config_path, 'r') as f:
        cfg = yaml.safe_load(f)
        
    # Overwrite the raw directory to point to our newly downloaded files
    cfg['dataset']['raw_dir'] = new_raw_dir
    
    # Save the updated config back to disk
    with open(config_path, 'w') as f:
        yaml.safe_dump(cfg, f)
    print(f"Updated config to use '{new_raw_dir}' as the raw dataset directory.")


#############################################################################################
#############################################################################################
def main():
    # 1. Configuration
    search_query = "heavy metal generated by AI"
    download_folder = "DNL"
    config_file = "config/config.yaml"
    number_of_songs_to_download = 100 # Adjust this based on how much data you want

    # 2. Download Data
   #  download_youtube_audio(search_query, download_folder, max_results=number_of_songs_to_download)

    # 3. Update the YAML config so train_vqvae knows where to look
    update_config_for_new_data(config_file, download_folder)
    
    # 4. Train the VQ-VAE (This will automatically run your preprocess_dataset)
    print("\n===========================================")
    print("      STARTING VQ-VAE TRAINING STAGE       ")
    print("===========================================")
    
    train_vqvae_main()
    
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        allocated = torch.cuda.memory_allocated() / (1024 ** 2)
        print(f"CUDA Memory cleared. Currently allocated: {allocated:.2f}MB")
    
 
    print("\n===========================================")
    print("     STARTING GENERATOR TRAINING STAGE     ")
    print("===========================================")
    train_generator_main()

if __name__ == "__main__":
    main()
    