dataset:
  duration_sec: 8
  train_chunks_per_file: 3
  duration_sec_train: 10
  sample_rate: 22050

generator:
  accumulation_steps: 8 
  embedding_dim: 512
  hidden_dim: 512
  lora_alpha: 32.0
  lora_dropout: 0.05
  lora_rank: 16
  num_embeddings: 1024
  num_heads: 8
  num_layers: 6
  sampling_temp: 0.7
  use_lora: true
  max_context: 1536

training:
  device: cuda
  gen_batch_size: 2
  gen_epochs: 40s
  lr: 0.0002
  vqvae_batch_size: 3
  vqvae_epochs: 15
  lr_step_size: 0    # decay every 20 epochs (set 0 to disable)
  lr_gamma: 0.5
  grad_clip: 1.0
  early_stop_patience: 0

vqvae:
  commitment_cost: 0.25          # was 0.25
  in_channels: 1
  embedding_dim: 512
  num_embeddings: 2048
  hidden_channels: 512
  residual_channels: 256
  num_residual_layers: 2
  stride: 16

